apiVersion: v1
kind: Secret
metadata:
  name: lab-crossplane-argocd-gitops-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: lab-crossplane-argocd-gitops
  url: ${URL_REPO}
  username: ${GITHUB_USERNAME}
  password: ${GITHUB_PAT}
